### PR TITLE
Build hardening

### PR DESCRIPTION
**Pull request by voltone**
All OTP builds use their respective OS default build flags, which means on older platforms the resulting executables are not sufficiently hardened. In particular, older Ubuntu and Debian versions are not compiled a Position Independent Executable, meaning they cannot take advantage of ASLR. H/T to @unthought for pointing this out.

*Note that I have done very little testing on the resulting binaries. Enabling PIE is known to break HiPE on older OTP versions, but then again, HiPE is broken on the latest OTP versions anyway. I am not aware of any negative impact of other hardening flags, and since the Ubuntu 20.04 build has all flags enabled out of the box it would seem to be safe to apply them elsewhere too...?*

The diffs below show the changes in the output of `hardening-check beam.smp` before and after the Dockerfile changes in this PR. The [hardening-check](http://manpages.ubuntu.com/manpages/focal/man1/hardening-check.1.html) tool is part of the 'devscripts' package on Ubuntu and Debian.

# Ubuntu

## Ubuntu 20.04 (Focal)

No change:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
 Read-only relocations: yes
 Immediate binding: yes
 Stack clash protection: yes
 Control flow integrity: yes

## Ubuntu 18.04 (Bionic)

No change:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
 Read-only relocations: yes
 Immediate binding: yes
 Stack clash protection: unknown, no -fstack-clash-protection instructions found
 Control flow integrity: unknown, no -fcf-protection instructions found!

'Stack clash protection' and 'Control flow integrity' require GCC 8.

## Ubuntu 16.04 (Xenial)

```diff
- Position Independent Executable: no, normal executable!
+ Position Independent Executable: yes
  Stack protected: yes
  Fortify Source functions: yes (some protected functions found)
  Read-only relocations: yes
- Immediate binding: no, not found!
+ Immediate binding: yes
  Stack clash protection: unknown, no -fstack-clash-protection instructions found
  Control flow integrity: unknown, no -fcf-protection instructions found!
```

'Stack clash protection' and 'Control flow integrity' require GCC 8.

## Ubuntu 14.04 (Trusty)

```diff
- Position Independent Executable: no, normal executable!
+ Position Independent Executable: yes
  Stack protected: yes
  Fortify Source functions: yes (some protected functions found)
  Read-only relocations: yes
- Immediate binding: no, not found!
+ Immediate binding: yes
  Stack clash protection: unknown, no -fstack-clash-protection instructions found
  Control flow integrity: unknown, no -fcf-protection instructions found!
```

'Stack clash protection' and 'Control flow integrity' require GCC 8.

# Debian

## Debian 10 (Buster)

```diff
  Position Independent Executable: yes
- Stack protected: no, not found!
- Fortify Source functions: no, only unprotected functions found!
+ Stack protected: yes
+ Fortify Source functions: yes (some protected functions found)
  Read-only relocations: yes
- Immediate binding: no, not found!
- Stack clash protection: unknown, no -fstack-clash-protection instructions found
- Control flow integrity: unknown, no -fcf-protection instructions found!
+ Immediate binding: yes
+ Stack clash protection: yes
+ Control flow integrity: yes
```

## Debian 9 (Stretch)

```diff
  Position Independent Executable: yes
- Stack protected: no, not found!
- Fortify Source functions: no, only unprotected functions found!
+ Stack protected: yes
+ Fortify Source functions: yes (some protected functions found)
  Read-only relocations: yes
- Immediate binding: no, not found!
+ Immediate binding: yes
  Stack clash protection: unknown, no -fstack-clash-protection instructions found
  Control flow integrity: unknown, no -fcf-protection instructions found!
```

'Stack clash protection' and 'Control flow integrity' require GCC 8.

## Debian 8 (Jessie)

```diff
- Position Independent Executable: no, normal executable!
- Stack protected: no, not found!
- Fortify Source functions: no, only unprotected functions found!
- Read-only relocations: no, not found!
- Immediate binding: no, not found!
+ Position Independent Executable: yes
+ Stack protected: yes
+ Fortify Source functions: yes (some protected functions found)
+ Read-only relocations: yes
+ Immediate binding: yes
  Stack clash protection: unknown, no -fstack-clash-protection instructions found
  Control flow integrity: unknown, no -fcf-protection instructions found!
```

'Stack clash protection' and 'Control flow integrity' require GCC 8.

# Alpine

## Alpine 3.12

```diff
  Position Independent Executable: yes
  Stack protected: yes
  Fortify Source functions: no, only unprotected functions found!
  Read-only relocations: yes
  Immediate binding: yes
- Stack clash protection: unknown, no -fstack-clash-protection instructions found
- Control flow integrity: unknown, no -fcf-protection instructions found!
+ Stack clash protection: yes
+ Control flow integrity: yes
```

'Fortify Source functions' not available/applicable in musl.

### CODE REVIEW

**Comment by voltone** [comment]
Note that the standalone OTP binaries for Ubuntu are taken from a 14.04 Docker image, and they are quite widely used (e.g. in https://github.com/actions/setup-elixir). Such users are impacted by the lack of ASLR even if they deploy the binaries to more modern Ubuntu version. Since 14.04 is obsolete, it may be worth considering publishing more modern binaries, that may offer there benefits (e.g. newer ABI)

**Comment by ericmj** [comment]
Does both Ubuntu Bionic and Focal set the flags by default?

> Note that I have done very little testing on the resulting binaries. Enabling PIE is known to break HiPE on older OTP versions, but then again, HiPE is broken on the latest OTP versions anyway. I am not aware of any negative impact of other hardening flags, and since the Ubuntu 20.04 build has all flags enabled out of the box it would seem to be safe to apply them elsewhere too...?

I can run some tests. Do you know the OTP versions where PIE and HiPE are incompatible?

> Note that the standalone OTP binaries for Ubuntu are taken from a 14.04 Docker image, and they are quite widely used (e.g. in https://github.com/actions/setup-elixir). Such users are impacted by the lack of ASLR even if they deploy the binaries to more modern Ubuntu version. Since 14.04 is obsolete, it may be worth considering publishing more modern binaries, that may offer there benefits (e.g. newer ABI)

It's hard to predict a version that is both sufficiently safe and is supported by all platforms that use it. But I guess we can add builds for every LTS version like we do for docker.

**Comment by ericmj** [comment]
Another question is if we should go back and rebuild old docker images and builds. If there is potential for breakage with things like HiPE then maybe we shouldn't.

**Comment by voltone** [comment]
> Does both Ubuntu Bionic and Focal set the flags by default?

Yes

> Do you know the OTP versions where PIE and HiPE are incompatible?

HiPE [release notes for 3.18](http://erlang.org/doc/apps/hipe/notes.html#hipe-3.18) say:

_Make hipe compiled code work on x86_64 (amd64) with OS security feature PIE, where executable code can be loaded into a random location. Old behavior, if hipe was enabled, was to disable PIE build options for the VM._

It was released as part of 21.0.

**Comment by voltone** [comment]
> Another question is if we should go back and rebuild old docker images and builds. If there is potential for breakage with things like HiPE then maybe we shouldn't.

So maybe just for 21+? That should cover the majority of users. But didn't Bob promise not to change existing images?

**Comment by voltone** [comment]
The JIT just got merged into OTP master. We may need to check if the build hardening flags, both OS defaults and custom settings in this PR, have some impact on JIT's ability to generate and run native code: after all, the purpose of hardening is often to make it harder to execute injected code. I'll try to do some smoke tests...

**Comment by ericmj** [comment]
> So maybe just for 21+? That should cover the majority of users. But didn't Bob promise not to change existing images?

The promise is to not change the underlying versions of packages we base the images on. But we may still update images for bug and security fixes in the build process itself, assuming we are confident we are minimizing potential breakage.

> The JIT just got merged into OTP master. We may need to check if the build hardening flags, both OS defaults and custom settings in this PR, have some impact on JIT's ability to generate and run native code: after all, the purpose of hardening is often to make it harder to execute injected code. I'll try to do some smoke tests...

Thanks!

**Comment by voltone** [comment]
JIT seems to work on Ubuntu Focal, with all the hardening that it does out of the box.

It doesn't work on Alpine, even without the CFLAGS change proposed in this PR. It seems to be an issue of glibc vs musl. Since `configure` does not detect this it does not fall back to building the traditional BEAM. So Alpine builds will break unless `--disable-jit` is set explicitly, at least until OTP adds Alpine support or automatic disabling of JIT in the build scripts. I can make a separate PR for that if you like.

**Comment by ericmj** [comment]
I think we can go ahead with this change if we only add the flags for OTP 21+. Let's leave the alpine changes in under the assumption that OTP fixes the musl issues in time for the OTP 24 release. If the musl issues are not fixed in time we will tackle that issue then.

It does not feel safe to go back and rebuild old images since we don't have any regression testing for our builds. If someone is willing to do this testing we could do it.

**Comment by voltone** [comment]
Ah, sorry, I suppose I should have clarified that in this PR: the JIT issue with Alpine was not related to musl, it was a missing dependency that was fixed with #61.

That issue did make me realise there might be a need for a smoke test at the end of each build. I guess if the OTP build produces an inoperable `erlc` it will be detected once the associated Elixir build fails. But it would be nice to add a step at the end of the build that just invokes the interpreter (`erl` or `elixir`) and prints "OK". I tried to add that to this PR, but it turns out to be quite difficult to run a local copy of Bob for testing changes to the build pipeline. Do you have some way of testing things before pushing, other than manually running a Docker build?

**Comment by ericmj** [comment]
> Ah, sorry, I suppose I should have clarified that in this PR: the JIT issue with Alpine was not related to musl, it was a missing dependency that was fixed with #61.

Oh right, forgot about that.

> Do you have some way of testing things before pushing, other than manually running a Docker build?

No unfortunately we don't have any better way of testing. But if you push it I can test it.

**Comment by ericmj** [comment]
We have added builds for all Ubuntu LTS versions: https://github.com/hexpm/bob/pull/68.

**Comment by voltone** [comment]
For OTP <21:
* On platforms where PIE is not enabled by default, we don't force it
* On platforms where PIE is enabled by default nothing changes

Basically the resulting build should be the same as before, with PIE enabled on modern OSs, and HiPE enabled/disable as decided by the OTP build script.

For OTP >=21 we enable PIE if it is not enabled by default. HiPE should work, unless disabled for some other reason, since OTP 21 includes the fix mentioned [here](http://erlang.org/doc/apps/hipe/notes.html#hipe-3.18)

**Comment by voltone** [comment]
Hey @ericmj, what do you think? Is this good to go? I did some manual testing with specific versions. Hopefully the smoke test will prevent pushing broken images, in case something does break. But if you have an environment where you can run through a bunch of versions automatically before deploying this, then I guess that would be good...

**Comment by ericmj** [comment]
@voltone Thanks for working on this! 💜

**Comment by ericmj** [comment]
This change is causing failures in the configure step on ARM machines:

```
> docker build -t hexpm/erlang-arm64:23.2.4-debian-buster-20201012 --build-arg ERLANG=23.2.4 --build-arg OS_VERSION=buster-20201012 --build-arg PIE_CFLAGS=-fpie --build-arg PIE_LDFLAGS=-pie -f /app/lib/bob-0.0.1/priv/scripts/docker/erlang-debian-buster.dockerfile /app/lib/bob-0.0.1/priv/scripts/docker
[...]
Step 16/29 : RUN ./configure --with-ssl --enable-dirty-schedulers
 ---> Running in 9afb7d23a0db
=== Running configure in /OTP/erts ===
./configure '--with-ssl' '--enable-dirty-schedulers' CFLAGS='-g -O2 -fstack-protector -fstack-clash-protection -fcf-protection=full -fpie' LDFLAGS='-Wl,-z,relro,-z,now -pie' --disable-option-checking --cache-file=/dev/null --srcdir="/OTP/erts"
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/OTP/erts':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: /OTP/erts/configure failed!
./configure: 353: kill: No such process
```

**Pull request merged**
