### PR TITLE
Build docs for OTP

### LINKED ISSUE #64: Maybe build erlang docs?
Hi,

Not sure if this was discussed before. The new 1.11 images don't seem to have erlang docs included. Maybe it's a good idea to consider?

image

My windows installation does have it included but awkwardly does not have colors support, although I'm using a terminal that's capable of showing colors, as can be seen in the above screenshot

image

### PR DESCRIPTION
**Pull request by wojtekmach**
Closes #64

We could build different formats (pdf, man, etc), I think we could start with just the chunks since now both Elixir & Erlang can display them in their respective shells.

### CODE REVIEW

**Comment by ericmj** [comment]
Nice! Should we do the same for the docker images? Would it increase the size of the image a lot?

**Comment by wojtekmach** [comment]
Yup, Ill look into it.

**Comment by ericmj** [comment]
@wojtekmach Did you investigate for the docker images or is there anything we can help with?

**Comment by wojtekmach** [comment]
I didn't, I'll look into it soon!

**Comment by wojtekmach** [comment]
@ericmj I took a first stab at building docs for docker images and here are the results for ubuntu groovy one:

before this patch:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
wojtekmach/erlang   23.1.2              cd7f0cbcef36        2 hours ago         177MB
```

after this patch:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
wojtekmach/erlang   23.1.2              ba2f610f563e        26 minutes ago      186MB
```

I think the benefits far outweighs the cost so I'm planning to update remaining docker files but please let me know if you have any concerns!

**Comment by ericmj** [comment]
> I think the benefits far outweighs the cost so I'm planning to update remaining docker files but please let me know if you have any concerns!

Agreed, please go ahead.

**Comment by wojtekmach** [comment]
I updated the scrips, the difference is actually even smaller, 177MB vs 180MB.

We're only generating the docs on OTP >= 23 because only there we have the `DOC_TARGETS` configuration.

Ready for another look!

**Review by ericmj — APPROVED** [review]

**Comment by ericmj** [comment]
This is such a good change that I think it's worth it to rebuild all OTP 23+ tarballs and images.

**Comment by wojtekmach** [comment]
@ericmj I think that a would be great, if you have a script handy to rebuild, please go ahead!

**Comment by ericmj** [comment]
I can do it.

**Pull request merged**
