### PR TITLE
update alpine version to 3.13.6 and 3.14.2

### PR DESCRIPTION
**Pull request by baseballlover723**
Tested this with one of my projects with Elixir 1.12.2 & 1.11.4, Erlang 24.0.6 & 23.3.4.7, and Alpine 3.13.6 & 3.14.2

### CODE REVIEW

**Comment by ericmj** [comment]
Please test against all supported erlang major versions, you don't have to test any elixir versions.

Currently the new images for debian bullseye are being built and tomorrow the debian slim images will be built so I am not sure when this update can be rolled out. Hopefully some time this weekend or next week, but unsure since I will be travelling.

**Comment by baseballlover723** [comment]
Additionally tested building Erlang images and doing the version smoke test with

- Erlang 22.3.4.21 Alpine 3.13.6: Passed
- Erlang 22.3.4.21 Alpine 3.14.2: Passed (but I think this wouldn't get built because of https://github.com/hexpm/bob/blob/7cd755a639b79ceefa06ddab81ffed3a03748369/lib/bob/job/docker_checker.ex#L109-L110)
- Erlang 21.3.8.24 Alpine 3.13.6: Passed
- Erlang 21.3.8.24 Alpine 3.14.2: Failed (but I think this wouldn't get built because of https://github.com/hexpm/bob/blob/7cd755a639b79ceefa06ddab81ffed3a03748369/lib/bob/job/docker_checker.ex#L109-L110)

**Comment by gmile** [comment]
Anything I could help with to get alpine `3.14.2` out? 🙏

**Comment by baseballlover723** [comment]
@ericmj any chance this can get merged now?

**Pull request merged**
